name: 'Bump Version and Release'

on:
  workflow_run:
    workflows: ["quake2ts CI"]
    types:
      - completed
    branches:
      - main

jobs:
  bump-version:
    name: 'Bump Version on main'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    defaults:
      run:
        working-directory: quake2ts
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v4'
        with:
          ref: main

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: '20'

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@v11.0.7'
        with:
          tag-prefix: 'v'
          major-wording: 'major,Major,breaking,Breaking'
          minor-wording: 'minor,Minor,feat,Feat,feature,Feature'
          patch-wording: 'patch,Patch,fix,Fix,fixes,Fixes'
          rc-wording: 'rc,pre,beta,alpha'  # For pre-releases
          skip-commit: 'true'
          skip-tag: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          PACKAGEJSON_DIR: 'quake2ts'

      - name: 'Sync versions'
        run: node packages/tools/sync-versions.js

      - name: 'Commit, Tag and Push'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "ci: bump version to ${{ steps.version-bump.outputs.newTag }} [skip ci]"
          git tag ${{ steps.version-bump.outputs.newTag }}
          git push origin HEAD:main --tags
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Create GitHub Release'
        if: ${{ steps.version-bump.outputs.newTag }}
        uses: 'softprops/action-gh-release@v2'
        with:
          tag_name: ${{ steps.version-bump.outputs.newTag }}
          name: Release ${{ steps.version-bump.outputs.newTag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
